services:
  chapel-attendance:
    build: .
    ports:
      - "4000:4000"
    volumes:
      - ./backend/prisma:/app/backend/prisma
      - ./backend/data:/app/backend/data
      - ./backend/.env:/app/backend/.env:ro
      - ./frontend/.env:/app/frontend/.env:ro
